Removed Trivy Scan Image Stage and added check tools stage

diff --git a/Day-5/java-cicd/Jenkinsfile b/Day-5/java-cicd/Jenkinsfile
--- a/Day-5/java-cicd/Jenkinsfile
+++ b/Day-5/java-cicd/Jenkinsfile
@@ -59,27 +59,13 @@ pipeline {
             }
         }
 
-        stage('Trivy Security Scan') {
+        stage('Check Tools') {
             steps {
-                echo "Running Trivy image security scan"
                 sh '''
-                    # Install Trivy if not present
-                    which trivy || (
-                        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | apt-key add -
-                        echo "deb https://aquasecurity.github.io/trivy-repo/deb generic main" | tee /etc/apt/sources.list.d/trivy.list
-                        apt-get update && apt-get install -y trivy
-                    )
-
-                    echo "Scanning image for vulnerabilities..."
-                    trivy image --exit-code 1 \
-                                --severity CRITICAL \
-                                --no-progress \
-                                ${APP_NAME}:${BUILD_NUMBER} || {
-                        echo "CRITICAL vulnerabilities found! Failing pipeline."
-                        exit 1
-                    }
-
-                    echo "No critical vulnerabilities found. Safe to push."
+                    which curl || echo "curl not found"
+                    which wget || echo "wget not found"
+                    which docker || echo "docker not found"
+                    which trivy || echo "trivy not found"
                 '''
             }
         }
